### ISSUE TITLE
Creation of PG15 and maintenance of PG10

### ISSUE THREAD

**Issue by michaelpq** [ossc-db/pg_hint_plan#109]
I think that we are a bit overdue in the creation of a branch for PG15, so I am planning to add one in the next couple of days.

Also, there are a bunch of items to close from what I can see, some of them related to PG10 on which I guess we should have a last release before dropping out definitely. So any patches we should apply should go down to 10 for the moment to be on-par with everything, I guess.

**Comment by rjuju** [comment]
+1 for branching PG15 soon, and doing a final pg10 release.

**Comment by mikecaat** [comment]
Thanks for working! Do you have any plan when to make new releases?

I was planning to make a new release of PG 15 soon, but thankfully some issues/PRs have been closed and worked on. So, I want to know your comments.

By the way, please let me know if you need rpm packaging environments. I can create rpms packages for RHEL7/8.

**Comment by mikecaat** [comment]
> Yes, we should do a release once we have a clean board of all the issues reported. New feature proposals could always be dealt after, I guess. This should take a few weeks at least, so perhaps January is a possibility?
OK, I understood.

> I don't think I have the permissions to post a release, actually.
Oh, can you see the button "Draft a new release"?
https://github.com/ossc-db/pg_hint_plan/releases

**Comment by rjuju** [comment]
FTR I do have the "Draft a new release" button, so permissions seem ok on my side.

**Comment by michaelpq** [comment]
> FTR I do have the "Draft a new release" button, so permissions seem ok on my side.

It does not seem I do, but one of us able to do so will be just fine :)

**Comment by michaelpq** [comment]
FYI, I am planning to create PG15 at the end of this week, to prepare for a release approximately in two weeks, around the 25th of January. This way, we'll have a bit of time to adjust for the next set of minor releases of Postgres (the opposite could be true as well, I guess).

**Comment by michaelpq** [comment]
The new branch PG15 has been created, with support for github actions added to it.
