### ISSUE TITLE
Planned release for the 25th of January

### ISSUE THREAD

**Issue by michaelpq** [ossc-db/pg_hint_plan#117]
Hello all,

As we are a bit overdue for a release, I am going to cut a new release on the 25th of January, approximately my time in the morning. I am going to do changes the same way as 4ffa97e:
- PG15 released under 1.5.0.
- PG14 bumped to 1.4.1
- PG13, PG12, PG11 bumped to 1.3.8.
- PG10 bumped to 1.3.7, which will be the last version for this branch.

PG10 will be retired from the github actions shortly after the release, so as it can rest in peace.  All the branches will gain new SQL files and updates to the tests to cover the upgrade paths. Tags will be added for all the branches once the releases are stable under github actions.

One the tags are pushed, we'll need to do something about publishing new RPMs which require CentOS. I am used to working with RPM specs but I don't have any environment to properly test that. It does not seem like I have the permissions that would allow me to get that uploaded to github and shape a release. Could somebody here (@horiguti or @SeinoYuki ?) take take of that?

**Comment by mikecaat** [comment]
Hi, thanks for working.

> One the tags are pushed, we'll need to do something about publishing new RPMs which require CentOS. I am used to working with RPM specs but I don't have any environment to properly test that. It does not seem like I have the permissions that would allow me to get that uploaded to github and shape a release. Could somebody here (@horiguti or @SeinoYuki ?) take take of that?

I can do it. I have RHEL8 environment.

**Comment by michaelpq** [comment]
> I can do it. I have RHEL8 environment and the permission to shape a release notes.

That would be great! I am going to do the legwork in the code tomorrow my time. Could you check that I did not mess up the specs?

**Comment by michaelpq** [comment]
@mikecaat I have just applied a set of patches for all the branches that will be able to handle the new releases. The main point was to correctly handle the upgrade paths. The specs should be OK, hopefully.

**Comment by mikecaat** [comment]
I created rpm files using the latest branches and I found it works. So, the specs should be OK. Additionally, all regression tests pass using Postgres with the rpm files.

```
# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.1 (Ootpa)

# test commit hash
# grep -r "(HEAD" log/rpmbuild/
log/rpmbuild/pg15.1_rhel8_pg_hint_plan_1.5.1_20230120_145122.log:9b84b1f (HEAD, refs/remotes/origin/PG15) Version 1.5.1
log/rpmbuild/pg14.6_rhel8_pg_hint_plan_1.4.1_20230120_145138.log:c26349d (HEAD, refs/remotes/origin/PG14) Version 1.4.1
log/rpmbuild/pg13.9_rhel8_pg_hint_plan_1.3.8_20230120_145154.log:4f3643f (HEAD, refs/remotes/origin/PG13) Version 1.3.8
log/rpmbuild/pg12.13_rhel8_pg_hint_plan_1.3.8_20230120_145212.log:2bd1a64 (HEAD, refs/remotes/origin/PG12) Version 1.3.8
log/rpmbuild/pg11.18_rhel8_pg_hint_plan_1.3.8_20230120_145228.log:be6d363 (HEAD, refs/remotes/origin/PG11) Version 1.3.8
log/rpmbuild/pg10.23_rhel8_pg_hint_plan_1.3.7_20230120_145243.log:f253134 (HEAD, refs/remotes/origin/PG10) Version 1.3.7

# created rpms files
# ls rpms/tool/
pg_hint_plan10-1.3.7-1.el8.x86_64.rpm              pg_hint_plan13-debuginfo-1.3.8-1.el8.x86_64.rpm
pg_hint_plan10-debuginfo-1.3.7-1.el8.x86_64.rpm    pg_hint_plan13-debugsource-1.3.8-1.el8.x86_64.rpm
pg_hint_plan10-debugsource-1.3.7-1.el8.x86_64.rpm  pg_hint_plan13-llvmjit-1.3.8-1.el8.x86_64.rpm
pg_hint_plan11-1.3.8-1.el8.x86_64.rpm              pg_hint_plan14-1.4.1-1.el8.x86_64.rpm
pg_hint_plan11-debuginfo-1.3.8-1.el8.x86_64.rpm    pg_hint_plan14-debuginfo-1.4.1-1.el8.x86_64.rpm
pg_hint_plan11-debugsource-1.3.8-1.el8.x86_64.rpm  pg_hint_plan14-debugsource-1.4.1-1.el8.x86_64.rpm
pg_hint_plan11-llvmjit-1.3.8-1.el8.x86_64.rpm      pg_hint_plan14-llvmjit-1.4.1-1.el8.x86_64.rpm
pg_hint_plan12-1.3.8-1.el8.x86_64.rpm              pg_hint_plan15-1.5.1-1.el8.x86_64.rpm
pg_hint_plan12-debuginfo-1.3.8-1.el8.x86_64.rpm    pg_hint_plan15-debuginfo-1.5.1-1.el8.x86_64.rpm
pg_hint_plan12-debugsource-1.3.8-1.el8.x86_64.rpm  pg_hint_plan15-debugsource-1.5.1-1.el8.x86_64.rpm
pg_hint_plan12-llvmjit-1.3.8-1.el8.x86_64.rpm      pg_hint_plan15-llvmjit-1.5.1-1.el8.x86_64.rpm
pg_hint_plan13-1.3.8-1.el8.x86_64.rpm

# test results
# grep -r "tests passed" log/regtest/| grep "All"
log/regtest/pg15.1_rhel8_pg_hint_plan_1.5.1_20230120_145342.log: All 17 tests passed.
log/regtest/pg14.6_rhel8_pg_hint_plan_1.4.1_20230120_145441.log: All 17 tests passed.
log/regtest/pg13.9_rhel8_pg_hint_plan_1.3.8_20230120_145546.log: All 16 tests passed.
log/regtest/pg12.13_rhel8_pg_hint_plan_1.3.8_20230120_145650.log: All 16 tests passed.
log/regtest/pg11.18_rhel8_pg_hint_plan_1.3.8_20230120_145754.log: All 16 tests passed.
log/regtest/pg10.23_rhel8_pg_hint_plan_1.3.7_20230120_145900.log: All 15 tests passed.
```

**Comment by michaelpq** [comment]
> I created rpm files using the latest branches and I found it works. So, the specs should be OK. Additionally, all regression tests pass using PostgreSQL which the rpm is installed.

Thanks for checking! So we should be good to go.

**Comment by michaelpq** [comment]
As planned, the tags have been now pushed:
REL15_1_5_0
REL14_1_4_1
REL13_1_3_8
REL12_1_3_8
REL11_1_3_8
REL10_1_3_7

**Comment by mikecaat** [comment]
Thanks! I created rpms for RHEL8 with against the tags.
If you have any idea about release notes, please let me know. I can create the draft of release notes.

**Comment by michaelpq** [comment]
> If you have any idea about release notes, please let me know. I can create the draft of release notes.

Oh, it looks like I have an access to editing this part here: https://github.com/ossc-db/pg_hint_plan/releases. I'll go fill in that tomorrow.

**Comment by michaelpq** [comment]
The release notes have been written, so let's close this.
