### ISSUE TITLE
cannot build against postgres master branch

### ISSUE THREAD

**Issue by neiaberau** [ossc-db/pg_hint_plan#122]
this is not high priority, just to let you know
building against postgres master branch, since yesterday I get:
(might be related to commit b448f1c8d8  in postgres master branch:  git show b448f1c8d8)

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -fPIC -fvisibility=hidden -I. -I./ -I/u01/app/postgres/product/16dev/include/server -I/u01/app/postgres/product/16dev/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2   -c -o pg_hint_plan.o pg_hint_plan.c
In file included from pg_hint_plan.c:4930:
core.c: In function ‘try_partitionwise_join’:
core.c:1371:20: error: too many arguments to function ‘build_child_join_rel’
 1371 |    child_joinrel = build_child_join_rel(root, child_rel1, child_rel2,
      |                    ^~~~~~~~~~~~~~~~~~~~
In file included from pg_hint_plan.c:29:
/u01/app/postgres/product/16dev/include/server/optimizer/pathnode.h:337:20: note: declared here
  337 | extern RelOptInfo *build_child_join_rel(PlannerInfo *root,
      |                    ^~~~~~~~~~~~~~~~~~~~
In file included from pg_hint_plan.c:4935:
make_join_rel.c: In function ‘pg_hint_plan_make_join_rel’:
make_join_rel.c:115:9: error: ‘SpecialJoinInfo’ has no member named ‘delay_upper_joins’
  115 |   sjinfo->delay_upper_joins = false;
      |         ^~
make: *** [<builtin>: pg_hint_plan.o] Error 1

**Comment by michaelpq** [comment]
The compilation has been fixed with 8e3b76a. Thanks for the report!
