### ISSUE TITLE
aws ec2 make fail

### ISSUE THREAD

**Issue by zouchengli** [ossc-db/pg_hint_plan#124]
Makefile:38: /usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk: No such file or directory
make: *** No rule to make target `/usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk'.  Stop.

**Comment by michaelpq** [comment]
> Makefile:38: /usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk: No such file or directory

You need to review your installation so as the development package of PostgreSQL is installed. In the most popular distributions, this would be postgresql-dev or postgresql-devel. Then, if needed, update your PATH to include pg_config.
