### ISSUE TITLE
Next release for pg_hint_plans

### ISSUE THREAD

**Issue by michaelpq** [ossc-db/pg_hint_plan#128]
Hi all,

Now that some dust has set on the last release and that PostgreSQL 16 is entering in its stability period, now would be a good time for thinking about the next release.  Here are my thoughts on the matter:

- Aim for a release around the same time as PostgreSQL 16 GA, between the end of September 2023 and mid October.
- New release of pg_hint_plan for PostgreSQL 16, integrating HEAD with upstream's to-be-created REL_16_STABLE
- Last release of pg_hint_plan for PostgreSQL 11 (?).
- Reduction of the pull requests, integrating new features with the new 16's version.
- While working on a9863af, I have noticed that there is a lot of cruft around the handling of hints in subtransactions, particularly because of the integration with resowners when cleaning up things for a COMMIT/ABORT. I think that we'd better rewrite this part of the engine and avoid a dependency to a resowner registered even when most users are not going to need it.

Thoughts?

**Comment by michaelpq** [comment]
So, here is an update from me here. As of today, I have:

- Created a new branch PG16, compatible with PostgreSQL 16, labelled with version 1.6.
- Added an automated job for PG16, and added it to all the other branches.
- PG10 has been dropped from the automated jobs of all the branches supported.
- Reworked and improved all the docs in English across 14~master, fixing typos. This has taken a bit of time but that was really overdue.
- Bumped all the versions of all the branches from 11~master. All the branches should be able to handle all the possible upgrade paths. All the RPM specs have been bumped and updated with the SQL scripts added.

At this stage, all the ground work has been done to allow a release. Unfortunately, we have a few issues hanging around. So I am going to look at that next.

@mikecaat Could you check the RPM generation for CentOS?

**Comment by michaelpq** [comment]
@rjuju Do you think that it could be able to post the HTML docs somewhere once the release happens?

**Comment by rjuju** [comment]
On Tue, 29 Aug 2023, 13:29 Michael Paquier, ***@***.***>
wrote:

> @rjuju <https://github.com/rjuju> Do you think that it could be able to
> post the HTML docs somewhere once the release happens?
>

it can yes, once someone takes care of
https://github.com/ossc-db/pg_hint_plan/pull/125#issuecomment-1469227005

>

**Comment by michaelpq** [comment]
I have little idea about the webhook part, but I suspect that I don't have the permissions to do so either. @horiguti or @mikecaat, could you comment ?

**Comment by mikecaat** [comment]
Thanks for working on the next release.

>@mikecaat Could you check the RPM generation for CentOS?

Yes, @SeinoYuki san will make RPM packages after all the RPM specs have been bumped. 

> I have little idea about the webhook part, but I suspect that I don't have the permissions to do so either. @horiguti or @mikecaat, could you comment ?

Unfortunately, only Admin can manage webhooks. I've checked [Manage webhooks and deploy keys](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization).

So, I'm going to a new webhook for the page of "Read the Docs". Please let me know the "Playload URL".  I've checked [Manual integration setup for GitHub](https://docs.readthedocs.io/en/stable/guides/setup/git-repo-manual.html#manual-integration-setup) and I will make the webhook with the following configuration.

* Playload URL: (Please let me know. You can see Admin > Integration pages in Read the Docs.)
* Content type: application/json 
* Secret: blank
* Event : Branch or tag creation, Branch or tag deletion, Pull requests and Pushes

If I have misunderstood, please let me know.

BTW, thanks for the work on polishing the documentation. The pg_hint_plan page of "Read the Docs" is readable and nice!

**Comment by rjuju** [comment]
@mikecaat it's probably not a good idea to publicly disclose the payload URL.  Ideally you could create an account on readthedocs and let me know either your email or account name and I will be able to give you maintainer privileges on the project.  That way you can check the payload URLs (there are 2 projects for english and japanese language), regenerate them if needed or any other configuration you think is appropriate.

**Comment by rjuju** [comment]
Oh, also please note that there are currently a few warnings about RTD configuration.  I haven't worked on that yet as it requires adding a new configuration file in the repository and I wasn't sure that we would do the integration.  I can work on that if you want, once the RTD integration is done.

**Comment by mikecaat** [comment]
> @mikecaat it's probably not a good idea to publicly disclose the payload URL. Ideally you could create an account on readthedocs and let me know either your email or account name and I will be able to give you maintainer privileges on the project. That way you can check the payload URLs (there are 2 projects for english and japanese language), regenerate them if needed or any other configuration you think is appropriate.

OK, I made my account ([mikecaat](https://readthedocs.org/profiles/mikecaat/)). Since I'm not familiar with "Read the Docs", it would be quicker if you handled it.

**Comment by rjuju** [comment]
Great, I just invited you as a maintainer on both projects!  You can find the github webhooks in the admin/integration menu.

**Comment by mikecaat** [comment]
Thanks! I've added two webhooks for the projects. The configuration seems to be working now. You can see "Webhook configured correctly" in admin>integrations>exchange.

**Comment by michaelpq** [comment]
> Oh, also please note that there are currently a few warnings about RTD configuration. I haven't worked on that yet as it requires adding a new configuration file in the repository and I wasn't sure that we would do the integration. I can work on that if you want, once the RTD integration is done.

While looking at that yesterday, I have noticed that one of these is caused by sphinx that does not like the '$' character in a SQL block, because this character is not allowed by the SQL specification, but our example shows a normalized query.

**Comment by michaelpq** [comment]
@mikecaat The Japanese documentation needs a refresh in the range of 14~HEAD to be completely correct.

**Comment by mikecaat** [comment]
> > > Oh, also please note that there are currently a few warnings about RTD configuration. I haven't worked on that yet as it requires adding a new configuration file in the repository and I wasn't sure that we would do the integration. I can work on that if you want, once the RTD integration is done.
> > 
> > 
> > While looking at that yesterday, I have noticed that one of these is caused by sphinx that does not like the '$' character in a SQL block, because this character is not allowed by the SQL specification, but our example shows a normalized query.
> 
> It seems that this is a known limitation in the Sphinx community. ([WARNING: Could not lex literal_block as "sql". Highlighting skipped.](https://github.com/sphinx-doc/sphinx/issues/3175))

I found 'plpgsql' lexer alias and it works. I made a PR to fix warnings (#149).
We can see [all lexer aliases](https://pygments.org/docs/lexers/) supported by Sphinx.

**Comment by mikecaat** [comment]
> > > > Oh, also please note that there are currently a few warnings about RTD configuration. I haven't worked on that yet as it requires adding a new configuration file in the repository and I wasn't sure that we would do the integration. I can work on that if you want, once the RTD integration is done.
> > > 
> > > 
> > > While looking at that yesterday, I have noticed that one of these is caused by sphinx that does not like the '$' character in a SQL block, because this character is not allowed by the SQL specification, but our example shows a normalized query.
> > 
> > 
> > It seems that this is a known limitation in the Sphinx community. ([WARNING: Could not lex literal_block as "sql". Highlighting skipped.](https://github.com/sphinx-doc/sphinx/issues/3175))
> 
> I found 'plpgsql' lexer alias and it works. I made a PR to fix warnings (#149). We can see [all lexer aliases](https://pygments.org/docs/lexers/) supported by Pygments which is used by Sphinx.

Pushed it to master, PG15 and PG14 branches.

**Comment by mikecaat** [comment]
> @mikecaat The Japanese documentation needs a refresh in the range of 14~HEAD to be completely correct.

I asked @yamatattsu san to take care of it. Please wait for his reply.

**Comment by michaelpq** [comment]
Okay, the last thing that I have on my list is #145 , where the use of the extended query protocol messes up with the hint execution. I am not sure that the suggested fix relying on the ExecutorRun() hook is completely right, TBH.

**Comment by yamatattsu** [comment]
> > @mikecaat The Japanese documentation needs a refresh in the range of 14~HEAD to be completely correct.
> 
> I asked @yamatattsu san to take care of it. Please wait for his reply.

@michaelpq @mikecaat 
Currently, we only have .po files for the Japanese document of HEAD. (It would be nice if the .po file could be used for PG14 and 15, but not sure.)
So, I'll refresh the Japanese documentation of HEAD by the mid-Oct. 
I think that there is no problem even if there is no Japanese document for PG14 and 15.

**Comment by rjuju** [comment]
I only bootstrapped the translation files for HEAD, but I did document how to do generate the .pot and .po files in docs/README so that anyone can easily start a new translation in any language for any branch.

**Comment by egashira-yusuke** [comment]
@michaelpq 
Sorry this is just before the new release, but we have confirmed that the issues fixed in 23cabaf902b09b6b4ed14f1f920f3ec57d7fcb68 also occur in versions prior to PG15.

- PostgreSQL 11.21 + pg_hint_plan PG11
- PostgreSQL 12.16 + pg_hint_plan PG12
- PostgreSQL 13.12 + pg_hint_plan PG13
- PostgreSQL 14.9 + pg_hint_plan PG14

Fortunately, 23cabaf902b09b6b4ed14f1f920f3ec57d7fcb68 seems to be able to apply cherry-pick to branches from PG11 to PG14.
If the next release to the PG11 branch is the final one for PostgreSQL 11 support, can you have this backpatch included in that release?
I will create a Pull-Request for this modification if necessary.

**Comment by michaelpq** [comment]
>  If the next release to the PG11 branch is the final one for PostgreSQL 11 support, can you have this backpatch included in that release?

I'll look at that on Monday, there are still a couple of days until PG16 is released ;)

**Comment by michaelpq** [comment]
@egashira-yusuke I have applied 23cabaf9 with all its related cleanup commits down to 11, with everything squashed in a single commit.

**Comment by egashira-yusuke** [comment]
@michaelpq Thank you for your prompt action.

**Comment by michaelpq** [comment]
The release has been published, with release notes, etc.

@mikecaat Could you publish some RPM packages?

**Comment by mikecaat** [comment]
Thanks! 

> @mikecaat Could you publish some RPM packages?

Yes, @SeinoYuki san plan to do so. Please wait a few days.

**Comment by SeinoYuki** [comment]
@michaelpq 
When I tried to create an RPM, I found a problem in the Makefile.
[No rule to make target 'doc/*'] was output.
I think docs is correct, not doc. This occurs in PG14, 15, 16, master.

```
TARSOURCES = Makefile *.c  *.h COPYRIGHT* \
	pg_hint_plan--*.sql \
	pg_hint_plan.control \
	doc/* expected/*.out sql/*.sql sql/maskout.sh \
	data/data.csv input/*.source output/*.source SPECS/*.spec
```


We are currently working on RPM generation for RHEL7 and will continue with RHEL8 and 9.

**Comment by SeinoYuki** [comment]
I am ready to release the rpm.
Sorry it took so long for the first time.

@michaelpq 
I would like to fix Release/TAG with a version that incorporates #138 before the RPM release.
Is there a problem if I update Release/TAG on my end?

Release RPM for PG16 is after the main PostgreSQL is released.
Is that okay?

**Comment by SeinoYuki** [comment]
[REL13_1_3_9](https://github.com/ossc-db/pg_hint_plan/tree/REL13_1_3_9), [REL12_1_3_9](https://github.com/ossc-db/pg_hint_plan/tree/REL12_1_3_9), [REL11_1_3_9](https://github.com/ossc-db/pg_hint_plan/tree/REL11_1_3_9) has been released.

**Comment by michaelpq** [comment]
> Is there a problem if I update Release/TAG on my end?
As long as the release notes include the same contents, no issues from me.

**Comment by SeinoYuki** [comment]
Updated Release/TAG and released rpms of REL14_1_4_2, REL15_1_5_1.
The PG16 version of the rpm will be released next Monday.

**Comment by SeinoYuki** [comment]
>The PG16 version of the rpm will be released next Monday.

RPM for [REL16_1_6_0](https://github.com/ossc-db/pg_hint_plan/releases/tag/REL16_1_6_0) has been released.

However, RHEL7 RPMs will not be released.
(The following announcement, RHEL7 RPMs is now EOL .)
https://yum.postgresql.org/news/rhel7-postgresql-rpms-end-of-life/
