### ISSUE TITLE
Issues that change to parallel execution plan when using hints

### ISSUE THREAD

**Issue by sminebu** [ossc-db/pg_hint_plan#13]
The default value of the parallel_tuple_cost parameter is 0.1. The value of the parallel_tuple_cost variable of pg_hint_plan is changed from 0.1 to 0 because it is of type int. This is why the execution plan changes in parallel when using pg_hint_plan.

**Comment by horiguti** [comment]
Thank you for the report. Fixed by the commit https://github.com/ossc-db/pg_hint_plan/commit/7dcc96fd27a7f91545156887faba5907f35da068 at master and back-patched up to PG95 branch.
