### ISSUE TITLE
multiple indexes for hints?

### ISSUE THREAD

**Issue by mahdiyari** [ossc-db/pg_hint_plan#155]
Hi,
How can I provide multiple indexes as the hint? Is this the correct form? Sometimes the query has one parameter less which makes the used index invalid for this query.
```
/*+ IndexOnlyScan(table index1 index2) */
```

**Comment by michaelpq** [comment]
Reading the docs explain the features:
https://pg-hint-plan.readthedocs.io/en/latest/hint_list.html

In this case, IndexOnlyScan is able to use a list of indexes:
```
IndexOnlyScan(table[ index...])
```

**Comment by mahdiyari** [comment]
So the syntax above is correct. There was no examples so I did doubt how would the list look like. Thanks.

**Comment by michaelpq** [comment]
Patches to improve the documentation are always welcome :)
