### ISSUE TITLE
Does pg_hint_plan support "unnamed_subquery" added as part of PG 16 ?

### ISSUE THREAD

**Issue by dcgadmin** [ossc-db/pg_hint_plan#159]
Does pg_hint_plan support "unnamed_subquery" added as part of PG 16 for sub-query without aliases for any hints on it like Rows?

**Comment by michaelpq** [comment]
I've not added anything like that, and I am not sure how much it would take to be able to do so.

If it proves to be useful, I don't see why we shouldn't do it.

**Comment by michaelpq** [comment]
I am not seeing a patch, but if you would like to submit something, feel free to send a pull request. For now I am closing this issue.
