### ISSUE TITLE
pg_hint_plan whether support  for hints for group by method(hash/sort)?

### ISSUE THREAD

**Issue by ZhiXingHeYiApple** [ossc-db/pg_hint_plan#171]
I have reviewed the documentation and issue list, but I couldn't find how to use the pg_hint_plan extension to force my `group by` SQL query to use hash aggregation. 
Like `/*+ use_hash_aggregation*/` hint will throw error about `pg_hint_plan: hint syntax error at or near "use_hash_aggregation"`

**Comment by michaelpq** [comment]
I am not sure what you exactly mean here, but perhaps that's an Oracle specific thing? If you can provide a patch (in which case a pull request would be most welcome, and/or a test case, that would be most interesting for somebody to look at your problem.

Without any resources to get that addressed, this ticket is going nowhere, so let's close it for now.
