### ISSUE TITLE
Hint to use a Nested Loop Semi Join

### ISSUE THREAD

**Issue by SteveDirschelTR** [ossc-db/pg_hint_plan#177]
I have a query that is joining into an EXISTS clause using a Hash Semi Join.  I think it will perform better if it would use a Nested Loop Semi Join but I don't see that hint available under the hint list, Join Method.  If this is not possible to hint could I request an enhancement to allow that hint (and vice versa where maybe the query is doing a Nested Loop Semi Join and I want it to do a Hash Semi Join).

**Comment by michaelpq** [comment]
Without a test self-contained test case, I doubt that I will be able to provide some help or check if this is a bug of some kind. If you can provide this information, let's dig into things, but without that, my time is limited enough that there is not much I'll be able to do.

Let's close the ticket for now as a lack of input. If you can provide all the information that would make an investigation easier to dig into, please feel free to reopen.
