### ISSUE TITLE
Cant get normalized text to work with pg plan hint

### ISSUE THREAD

**Issue by fakdaddy75** [ossc-db/pg_hint_plan#180]
Posted issue here.
https://dba.stackexchange.com/questions/338270/performance-issue-cant-fix-with-pg-plan-hints

I can send code.
I've tried 4-5 variations of the normalized text.

Tracing shows its not being matched in hint table on lookup.

**Comment by michaelpq** [comment]
If the link you are pointing to loses its contents, we'll have no way to know what action needs to be taken here. Please provide a self-contained test case for the problem you are pointing to.

FWIW, I see nothing really actionable here, so I'm closing this ticket out of information. #190 is not something that will be backpatched.
