### ISSUE TITLE
Maskout script doesn't work on macOS

### ISSUE THREAD

**Issue by Sanath97** [ossc-db/pg_hint_plan#181]
Maskout script used for tests `maskout.sh` doesn't seems to work on MAC machines. Particularly, issue is with `sed` command and script fails to mask cost/width values in the query plan.  Instead we found below `sed` seems to work with both macOS and Linux machine(tested on Ubuntu).

`sed -E 's/cost=10{7}[\.0-9]+ /cost={inf}..{inf} /;s/cost=[\.0-9]+ /cost=xxx..xxx /;s/width=[0-9]+([^0-9])/width=xxx\1/;s/^ *QUERY PLAN *$/  QUERY PLAN/;s/^--*$/----------------/'`

**Comment by michaelpq** [comment]
Yes, I want to replace the dependency to these two maskout shell scripts to a SQL function able to filter out the output of EXPLAIN, as we do in PostgreSQL for the main regression test suite. I'll see about doing this cleanup in the next few days for the upcoming release.

**Comment by michaelpq** [comment]
What I am referring here is to have an equivalent of explain_filter() in src/test/regress/sql/explain.sql, just that we'd define it in the init script here.

**Comment by michaelpq** [comment]
The shell scripts have been removed from master and PG17 as of  9fad1e391416, meaning that this issue is fixed.
