### ISSUE TITLE
Next release of pg_hint_plan with PostgreSQL 17 compatibility

### ISSUE THREAD

**Issue by michaelpq** [ossc-db/pg_hint_plan#190]
Hi all,

I have that on my tablets for some time. Let's do a new release of this module at the same time as PostgreSQL 17. I have on my TODO list a few things, as of:

1. Finish any compatibility work required for HEAD.
2.  Fork a new branch called PG17, with changes on HEAD to plug in PG18.
3.  Feature: plug-in query IDs rather than query string normalizations for the hint table. This has been on the table for some time, and I really want to get rid of that entirely now that query IDs are compiled in core, included for utilities.
4. Feature: Introduce a proper parser for the hint strings. bfb45447c9d4 has done most of the work to be able to extract the hints, but we still need to translate the hints to binary trees, which is something that the code now does with some manual steps in the hint type callbacks.
5. A round table of existing bugs, to see what could be addressed.
6. More work and analysis is needed for a3646e1b073c, which is still on HEAD. This has been reverted from the back-branches following plan instabilities as of bfaabf161824, and I think it's not quite safe yet in terms of parallel handling. 
7. This will be the last release for PG12, with PostgreSQL 12 compatibility, following upstream that will EOL it. So let's be   very careful to not break anything on this branch.

The release would be planned for September, potentially in its 2nd week but let's be flexible about that, just before PostgreSQL GA. In terms of features, I think that I'll be able to tackle item 3, not sure about 4.

If @yamatattsu , @rjuju or any others have any comments, feel free.

**Comment by andyatkinson** [comment]
Looking forward to trying out new changes! I'm sure @FranckPachot would be interested as well.

**Comment by yamatattsu** [comment]
Hi Michael-san!


> 3. Feature: plug-in query IDs rather than query string normalizations for
> the hint table. This has been on the table for some time, and I really want
> to get rid of that entirely now that query IDs are compiled in core,
> included for utilities.


Does it mean the query string normalization column on the hint table will
be removed and
the query_id column will be added on the table instead?

The release would be planned for September, potentially in its 2nd week but
> let's be flexible about that, just before PostgreSQL GA. In terms of
> features, I think that I'll be able to tackle item 3, not sure about 4.
>
> If @yamatattsu <https://github.com/yamatattsu> , @rjuju
> <https://github.com/rjuju> or any others have any comments, feel free.
>
For now, The schedule seems fine for me.
I'd like to add this item to the TODO list:
    6. Add new Japanese translation file (*.po) for the document

**Comment by samimseih** [comment]
> Feature: plug-in query IDs rather than query string normalizations for the hint table. This has been on the table for some time, and I really want to get rid of that entirely now that query IDs are compiled in core, included for utilities.


#3 is a really important feature IMO as the current hint_table is hard to use when dealing with large sql text or the same sql text that could have differences in comments and white space. 

Just a thought on this feature:

I do think there needs to be a column that tracks the last time the hint was used. IMO, there are existing reasons a last_used is important to have, but especially with queryId changing if a table is dropped and recreated, pg_dump, etc., the user will need to perform maintenance on the table and remove no longer valid queryIds. Of course there is an overhead to continually updating a last_used, and I don't think that accuracy is required here ( maybe update last_used every so often ).


Regards,

Sami Imseih

**Comment by fakdaddy75** [comment]
Cant wait for the query_id enhancement.  thx

**Comment by michaelpq** [comment]
> Does it mean the query string normalization column on the hint table will be removed and the query_id column will be added on the table instead?

Yes, it means to wipe out entirely this dependency from the tree. It would still be possible to cross-check the normalized string with pg_stat_statements, which is something that most users use anyway these days for monitoring.

**Comment by yamatattsu** [comment]
Hi Michael-san and Sami,

Yes, it means to wipe out entirely this dependency from the tree. It would
> still be possible to cross-check the normalized string with
> pg_stat_statements, which is something that most users use anyway these
> days for monitoring.


Ah, I see.
In other words, pg_stat_statements is required as a prerequisite for using
the hint table of
pg_hint_plan. Right?

#3 <https://github.com/ossc-db/pg_hint_plan/issues/3> is a really important
> feature IMO as the current hint_table is hard to use when dealing with
> large sql text or the same sql text that could have differences in comments
> and white space.


As an extra information, pg_plan_advsr automatically generates normalized
query strings and
automatically registers them in the hint table for use.
I don't understand the issue with normalized query strings in detail, but
if you are having trouble with it,
you might want to try pg_plan_advsr.

**Comment by michaelpq** [comment]
> I don't understand the issue with normalized query strings in detail, but if you are having trouble with it,

Duplication. The normalization code in pg_hint_plan is a copy-paste of pg_stat_statements.

I can see what you are getting at with pg_plan_advsr as it relies on pg_hint_plan's normalize_query.h. Still it looks like the same thing to me. Is there any point in normalizing the query if we have a query ID. Perhaps that's an overoptimistic assumption, but we can assume that pg_stat_statements is used, meaning that the query would be normalized and that it would be able to retrieve that with a join? @rjuju , thoughts?

**Comment by rjuju** [comment]
well, there's an assumption that *some* normalisation stuff is installed, as now pg_stat_statements can work with custom algorithm. so in theory if your use case is to add hints on queries touching temp tables because you don't issue vacuum and you know that a certain plan is better it could be a good idea to rely on a custom jumbling approach that computes a query identifier based on the relation names for temp tables so that you can actually have a stable queryid.
I'm not sure how much we rely on having the normalised query string available (either in this extension or pg_plan_asvsr), but if for some reason pgss isn't an option users could also hack a simplified version that only stores the normalised query string, which could made way more efficient than pgss and the garbage collection approach.

**Comment by michaelpq** [comment]
>  I'm not sure how much we rely on having the normalised query string available (either in this extension or pg_plan_asvsr), but if for some reason pgss isn't an option users could also hack a simplified version that only stores the normalised query string, which could made way more efficient than pgss and the garbage collection approach.

pg_hint_plan uses the normalized query to do lookups of the hint table, using the same normalization as pg_stat_statements where the comments don't matter. There's a point that this reduces debugging if relying only on the normalized string if looking at the hint table, but honestly I'm going to hang on my argument about "let's just use pg_stat_statements" for the mapping and do JOINs, reducing the bloat of the hint table if using long query strings. We're paying twice the normalization costs, currently.

**Comment by rjuju** [comment]
my point was more with the curent plan of relying on the queryid only. if we do that there's no need for the query string or normalised query string right? so there would be no need for pgss either, just enable core queryid computation or install a custom one that better suits your needs.

**Comment by yamatattsu** [comment]
>
> I can see what you are getting at with pg_plan_advsr as it relies on
> pg_hint_plan's normalize_query.h. Still it looks like the same thing to me.
> Is there any point in normalizing the query if we have a query ID. Perhaps
> that's an overoptimistic assumption, but we can assume that
> pg_stat_statements is used, meaning that the query would be normalized and
> that it would be able to retrieve that with a join?


Ah, right, pg_plan_advsr uses pg_hint_plan's normalize_query.h. I thought
the problem was that it was difficult to create a normalized query string,
so I proposed to use pg_plan_advsr. But I understand that it is not the
problem on this thread.


I'm going to hang on my argument about "let's just use pg_stat_statements"
> for the mapping and do JOINs, reducing the bloat of the hint table if using
> long query strings. We're paying twice the normalization costs, currently.


The problem here is two things like:
  1. reducing the bloat of the hint table by long query text
  2. reducing the costs of normalization string
Is my understanding right?
If so, using queryid based on compute_query_id on PG core seems better to
solve the problems.

P.S.
pg_plan_advsr uses queryid by using compute_query_id since PG14, so I guess
it's okay to use it in the hint table.

**Comment by michaelpq** [comment]
> This is just on real-world case in which having a queryId will be very useful. There are other cases such as adding whitespace or a linebreak in the query text. All such queries will end up with the same queryId, but the hints table currently is not able to recognize this.

From the point where the hint table requires the values to be inserted, providing a 64b value is just going to be less error-prone because there are less contents to manipulate..

**Comment by michaelpq** [comment]
> The problem here is two things like: 1. reducing the bloat of the hint table by long query text 2. reducing the costs of normalization string Is my understanding right? If so, using queryid based on compute_query_id on PG core seems better to solve the problems.

Thanks. As far as I can see, there are no major objections about that. I will send a patch that does the switch in the hint table then, tweaking the docs that query ID  values inserted in the hint table to match with the entries in pg_stat_statements.

**Comment by fakdaddy75** [comment]
Thanks. As far as I can see, there are no major objections about that. I will send a patch that does the switch in the hint table then, 
tweaking the docs that query ID values inserted in the hint table to match with the entries in pg_stat_statements.
==================================

From my lonely perspective this is perfect. Works like oracle using a statement id or hash.

Here's a real world example - no-one has been able to make it work. Meaning - postgres user groups, myself and a consultancy
Never finds a text match in hint_table ...... noone knows what it should be as we cant expose the normalized query $1 the recursive optimizer is looking for.

https://github.com/ossc-db/pg_hint_plan/issues/180

thanks Michaelpq !!

**Comment by michaelpq** [comment]
I have begun my butcher work for this release, and began with two things:

1. Stabilization of the regression tests. A few things have changed in upstream, for the best actually. I have applied these directly to allow the code to run installcheck.
2. As promised, a patch to integrate query IDs in the hint table: https://github.com/ossc-db/pg_hint_plan/pull/193.

**Comment by yamatattsu** [comment]
>
> /*+ APPLICATION 2 */ SELECT * FROM t1 WHERE t1.id = ?;
>


postgres=# SELECT *
> postgres-# FROM t1 WHERE t1.id = 1;



Thanks for the clarification! I understand the problems.

**Comment by yamatattsu** [comment]
Michael-san,


> 2. As promised, a patch to integrate query IDs in the hint table: #193
> <https://github.com/ossc-db/pg_hint_plan/pull/193>.


FYI:
I talked about using query_id in the hint table with Horiguchi-san today,
and He has no objections.
So, It's okay from us. :-D

**Comment by michaelpq** [comment]
> So, It's okay from us. :-D

If you have any questions, we can talk about that on Friday in live.

**Comment by yamatattsu** [comment]
>
> If you have any questions, we can talk about that on Friday in live.
>
>
Sounds good! Thanks.

**Comment by devrimgunduz** [comment]
What is the status in here? v17 beta2 is already out.

**Comment by michaelpq** [comment]
> What is the status in here? v17 beta2 is already out.

Still need a bit of time, but I am towards a release by the end of August with the core changes pushed by the end of next week, before brushing what I can from the bug list. I don't have more plans for in-core changes with the module for this release, only bug fixes.

**Comment by michaelpq** [comment]
Looking at my calendar, I am proposing the 29th of August for the tarball release. @devrimgunduz

**Comment by michaelpq** [comment]
The branches have been structured and prepared for the upcoming release, and a new PG17 branch has been created with a github action job for automated tests. At this point it would be only a matter of tagging and creating the tarballs.

Now is time for the real action: clean up of the existing bug list and address issues.
I also have on my list to reassess a3646e1b073c as it has been impacting the plan stability of some customer cases. This may finish by being reverted.

**Comment by devrimgunduz** [comment]
So, ping :-)

**Comment by michaelpq** [comment]
> So, ping :-)

Yep. I'm aware of that. But my schedule does not give me the possibility to get back to that until the 17th of August. So.

**Comment by yamatattsu** [comment]
Hi Michael-san,

I finished updating .po files for the next release on PG17 branch.

https://github.com/ossc-db/pg_hint_plan/commit/77573744006c2173cb132ed7d1fcaca7fc1d7db1

Thanks,
Tatsuro Yamada

**Comment by michaelpq** [comment]
> I finished updating .po files for the next release on PG17 branch.

Thanks Yamada-san!

**Comment by SeinoYuki** [comment]
Thanks.

> Looking at my calendar, I am proposing the 29th of August for the tarball release.
When the release page is created, @shinyaaa will upload the RPMs for RHEL 8/9.

**Comment by michaelpq** [comment]
Here is an update. I have most of the things I wanted to tackle for the moment in the tree, remains:
- https://github.com/ossc-db/pg_hint_plan/issues/161, this is not really mandatory for this release, and it requires more careful redesign of the tests.
- https://github.com/ossc-db/pg_hint_plan/issues/195, where I've asked for more input, because there is no way I am going to spend time second-guessing things.
- https://github.com/ossc-db/pg_hint_plan/issues/191, where the patch should be simple, and involve a check that the extension exists.
- https://github.com/ossc-db/pg_hint_plan/issues/187, this one is something I'd rather treat as a new feature. I'm working with someone else to see what we could do here, only for v18~ so no impact for the upcoming release.

Hence in all that, I just have #191 that should get its backpatch.

**Comment by michaelpq** [comment]
The tags have been pushed, the release notes have been written, the release has been pushed to PGXN and the release announcement has been sent to pgsql-announce, currently being hold for moderation.

So my job here is done. @shinyaaa, could you upload the RPMs, please?

**Comment by shinyaaa** [comment]
@michaelpq Thank you! I've uploaded the RPMs.

**Comment by michaelpq** [comment]
Cool, issue closed.
