### ISSUE TITLE
Hint IndexScan: more docs and (possibly) check names

### ISSUE THREAD

**Issue by danolivo** [ossc-db/pg_hint_plan#196]
I rarely use pg_hint_plan. So, my apologies if you have already fixed that.
If a query contains:
.. FROM table AS <smth> ..
the IndexScan hint will search for <smth>, not for the real table name. It should be explained in the documentation.
Moreover, it's worth considering implementing error handling for scan hints. The tool is case-sensitive, treating 'TABLE' and 'table' as different names. While all names during the query -> parsetree process are forced to be in lowercase, not all users may be aware of this. To enhance user confidence, it could be beneficial to check the existence of the table and index mentioned by the hint in the query. After all, the Set() hint throws an error in the case of an incorrect GUC name, so why not do the same for scan hints?

**Comment by danolivo** [comment]
I don't have it in code right now. But if you can apply a pull request, I would gladly write the code; it looks pretty simple.

**Comment by michaelpq** [comment]
I can review, edit and apply pull requests. I have commit rights on this repository.

**Comment by michaelpq** [comment]
For now, please note that I am closing the bug as of a lack of activity. If you'd like to improve the documentation and/or the code, please feel free to send a pull request or a patch.
