### ISSUE TITLE
no longer compiles on postgres master

### ISSUE THREAD

**Issue by neiaberau** [ossc-db/pg_hint_plan#197]
I gues this is low prio, but as a heads up

I get
core.c:1381:41: error: too few arguments to function ‘build_child_join_rel’
                                   child_joinrel = build_child_join_rel(root, child_rel1, child_rel2,

this commit on postgres master seems to have broken it:

git show --stat 513f4472a4a
commit 513f4472a4a0d294ca64123627ce7b48ce0ee7c1
Author: Richard Guo <rguo@postgresql.org>
Date:   Mon Jul 29 11:35:51 2024 +0900

    Reduce memory used by partitionwise joins

    In try_partitionwise_join, we aim to break down the join between two
    partitioned relations into joins between matching partitions.  To
    achieve this, we iterate through each pair of partitions from the two
    joining relations and create child-join relations for them.  With
    potentially thousands of partitions, the local objects allocated in
    each iteration can accumulate significant memory usage.  Therefore, we
    opt to eagerly free these local objects at the end of each iteration.

    In line with this approach, this patch frees the bitmap set that
    represents the relids of child-join relations at the end of each
    iteration.  Additionally, it modifies build_child_join_rel() to reuse
    the AppendRelInfo structures generated within each iteration.

    Author: Ashutosh Bapat
    Reviewed-by: David Christensen, Richard Guo
    Discussion: https://postgr.es/m/CAExHW5s4EqY43oB=ne6B2=-xLgrs9ZGeTr1NXwkGFt2j-OmaQQ@mail.gmail.com

 src/backend/optimizer/path/joinrels.c | 15 +++++++++++----
 src/backend/optimizer/util/relnode.c  | 18 +++---------------
 src/include/optimizer/pathnode.h      |  3 ++-
 3 files changed, 16 insertions(+), 20 deletions(-)

**Comment by michaelpq** [comment]
> core.c:1381:41: error: too few arguments to function ‘build_child_join_rel’
> child_joinrel = build_child_join_rel(root, child_rel1, child_rel2,

Thanks. You will likely note as well that the regression tests are failing on HEAD. Good thing that PG17 has been created not long ago..

**Comment by michaelpq** [comment]
This has been fixed with 01253bec29b5, requiring one run of update_copied_funcs.pl.
