### ISSUE TITLE
Failed while running ut-W.sql regression test

### ISSUE THREAD

**Issue by Dagouhan** [ossc-db/pg_hint_plan#20]
Hi.

When I was doing regression tests for pg_hint_planREL96_1_2_4, one case failed.

Platform information:
OS Version : RHEL 6.4
Posgresql version : 9.6.11
pg_hint_plan version :  96_1.2.4
Failure case : ut-W

In Posgresql-9.6.10, this case is passable. I guess this is a styling change caused by the upgrade of Posgresql . If so, in the Posgresql-9.6.11, does the expected log need to be updated？

Here is the testlog I actually tested.
[ut-W.zip](https://github.com/ossc-db/pg_hint_plan/files/2708175/ut-W.zip)

**Comment by horiguti** [comment]
It should stem from long file name in the "Foreign File:" line. It is fixed in PG96 and earlier by the commit https://github.com/ossc-db/pg_hint_plan/commit/88d3fb3e9d4b4cf344ba1e81049f953674a54b47,  and in PG10 and later by another way.
