### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by MironAtHome** [ossc-db/pg_hint_plan#201]
Microsoft Visual Studio 2022

Build and install postgres release 14 stable

Using branch PG14 of pg_hint_plan repository

Compile:
`cl.exe /c /I ..\..\..\..\app\pgsql14\include /I ..\..\..\..\app\pgsql14\include\server /I ..\..\..\..\app\pgsql14\include\server\port /I ..\..\..\..\app\pgsql14\include\server\port\win32 /I ..\..\..\..\app\pgsql14\include\server\port\win32_msvc /c /nologo /W3 /WX- /diagnostics:column /O2 /D WIN32 /D _WINDOWS /D __WINDOWS__ /D__WIN32__ /D WIN32_STACK_RLIMIT=4194304 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D BUILDING_MODULE /D _MBCS /GF /Gm- /EHsc /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo".\pg_hint_plan" /external:W3 /Gd /TC /wd4018 /wd4244 /wd4273 /wd4102 /wd4090 /wd4267 /FC /errorReport:queue /MT pg_hint_plan.c`

Link:
`link.exe /OUT:".\pg_hint_plan.dll" /INCREMENTAL:NO /NOLOGO ..\..\..\..\app\pgsql14\lib\postgres.lib kernel32.lib /TLBID:1 /DYNAMICBASE:NO /NXCOMPAT /MACHINE:X64 /ignore:4197 /DLL /NODEFAULTLIB:libc pg_hint_plan.obj queryjumble.obj`

Install following documentation
Example of "not working":
![image](https://github.com/user-attachments/assets/1bebe7ad-ec95-4b6d-9ede-5945a667cd75)
Will be debugging and sharing updates.

**Comment by michaelpq** [comment]
I have no idea what you are using for the builds, and we don't release builds on Windows, at least officially.

So, shrug, if you cannot provide more details. The regression tests do work fine.

**Comment by MironAtHome** [comment]
> and we don't release builds on Windows, at least officially

I am not sure how official will be result of this investigation, but it's going to
1. work. as good as "official"
2. easy enough for anyone to repeat

**Comment by michaelpq** [comment]
> I am not sure how official will be result of this investigation, but it's going to

Sure, I don't mind keeping this ticket open for some time. However, there is nothing really actionable, and I've heard about one company in Japan that offers builds on Windows for this module: https://www.sraoss.co.jp/tech-blog/pgsql/pg_hint_plan/

And it works for them, so there are hints that we have no reason to keep this ticket open at all, at the end.

**Comment by MironAtHome** [comment]
Great thanks, @michaelpq 
I looked over the page and wasn't able to find link to something like download or code repository. Perhaps needs a second look :)
Was able to build and install on my local postgres copy and confirm expected correct behavior of the code above.
![image](https://github.com/user-attachments/assets/678c4399-a4c1-449e-9e6f-26acb04d66c4)
The next few days I should have some answers, unless I can get to solution you helped me above from SRA OSS.
Once again, great thanks for assistance.

**Comment by MironAtHome** [comment]
Looks like the fix was fairly straightforward.
Just needed to add PGDLLEXPORT macro to the functions
_PG_init
_PG_fini
both, declaration and definition.
However, since function _PG_init is declared in the include file server\plpgsql.h, provided by postgres it needs also a similar fix to function declaration, to prevent compiler error
pg_hint_plan.c(667,19): error C2375: '_PG_init': redefinition; different linkage

**Comment by michaelpq** [comment]
>  Just needed to add PGDLLEXPORT macro to the functions _PG_init and _PG_fini.

fmgr.h in the PostgreSQL code tree does already that, no?
