### ISSUE TITLE
Error compiling on Solaris

### ISSUE THREAD

**Issue by Dagouhan** [ossc-db/pg_hint_plan#21]
Hi

When I compiled on Solaris, I encountered a compilation error.
Platform information:
OS Version : Solaris10
pg_hint_plan version : 96_1.2.4

The error message is as follows:
···· -Wl,--build-id  -G -o pg_hint_plan.so pg_hint_plan.o
ld: error: unrecognized option '--'
ld: error: use the -z help option for usage information
gmake: *** [pg_hint_plan.so] Error 2

After consulting the relevant information, we found that Solaris does not currently seem to support the following options in the Makefile.
> LDFLAGS+=-Wl,--build-id

If so, the following code seems to avoid this problem

`ifeq ($(shell uname), SunOS)`
`else`
`LDFLAGS+=-Wl,--build-id`
`endif`

**Comment by LittleWuCoding** [comment]
I have met your problem，too. The 'LDFLAGS+=-Wl,--build-id' option is for rpm building in Linux like OS.
So, the SunOS is not native support the option. What we do is just remove this option ,cause we do not need a rpm format pg_hint_plan.

**Comment by horiguti** [comment]
Thanks! I'm not sure it actually works but blindly applied it (with a small change) on master (PG12) and PG11 branches.

https://github.com/ossc-db/pg_hint_plan/commit/85e97821b11dde0f57f543c0b1f407f871799d9b
