### ISSUE TITLE
System crash on Row(<empty string>)

### ISSUE THREAD

**Issue by kaigai** [ossc-db/pg_hint_plan#24]
I could get a system crash on PostgreSQL v9.6 + pg_hint_plan 1.2.5 (for PGv9.6)
when I told the hint-clause below.

```
/*+
 Row()
 */
```
It is fundamentally a syntax error, so I expect it shall be ignored or aborted by error.
I guess something like list or cstring are not handled correctly in this corner case.

**Comment by horiguti** [comment]
It is a long standing bug of the parser for Rows hint. Fixed it at the commit https://github.com/ossc-db/pg_hint_plan/commit/dd5ea9685ee83db934eab9ed8203f44b0b2f5cac and back-patched up to 94. Thaks for reporting.
