### ISSUE TITLE
Segmentation fault occured with multi statements query

### ISSUE THREAD

**Issue by fhouillo** [ossc-db/pg_hint_plan#25]
Hello,

A segmentation fault occurs if `enable_hint_table = on` and a "multi-statement" query is used with some constants. 

Sample steps to reproduce: 

```
LOAD 'pg_hint_plan';
create extension pg_hint_plan;
set  pg_hint_plan.enable_hint_table = on;
\;\;SELECT 1,2;

> server closed the connection unexpectedly
```
It happens:
* with Postgres version >=PG10
* on pg_hint_plan branch >=PG10
* since the commit [Took in several improvements of pg_stat_statements](https://github.com/ossc-db/pg_hint_plan/commit/e3b976c5c3ab16d802666b51431384f93697c9d8).

The segmentation fault occurs in the function `generate_normalized_query` (file pg_stat_statements.c) with the code : 
`memcpy(norm_query + n_quer_loc, query + quer_loc, len_to_wrt);`
because `len_to_wrt` is negative.

According to the [commit](https://github.com/postgres/postgres/commit/83f2061dd037477ec8479ee160367840e203a722#diff-149c8b739d3114dc61922b6baef60e2e) in pg_stat_statements extension, it looks like the `query` parameter should be changed according to the new parameter `query_loc`, but pg_hint_plan.c always calls this function with the same query string.

**Comment by horiguti** [comment]
Thanks for the report. It is fixed by the following commit in master and back patched up to PG10.

https://github.com/ossc-db/pg_hint_plan/commit/de7600e460d1f773cb6e4a8ff1b1a96668b84307
