### ISSUE TITLE
pg_hint_plan for Postgres 12?

### ISSUE THREAD

**Issue by dimv36** [ossc-db/pg_hint_plan#37]
Hi, do you planning to create pg_hint_plan extension for Postgres 12?

**Comment by michaelwu0505** [comment]
Thank you for the great work! pg_hint_plan is very useful to me.

Now that Postgres 12 has been released, I am also interested to know if pg_hint_plan will support Postgres 12?

**Comment by horiguti** [comment]
Currently the master branch can compile against PG12 and regression test passes.  I'll release it soon after some further equipment and fix.

**Comment by horiguti** [comment]
Old issue. Close.
