### ISSUE TITLE
Please update pg_hint_plan.html in this Repo

### ISSUE THREAD

**Issue by robins** [ossc-db/pg_hint_plan#38]
Please update pg_hint_plan.html in this github Repository

I see that the Web page (http://pghintplan.osdn.jp/pg_hint_plan.html) doesn't reflect the source in the pg_hint_plan.html - https://github.com/ossc-db/pg_hint_plan/blob/master/doc/pg_hint_plan.html

Let me know if they are not supposed to match :( 

Thanks

**Comment by robins** [comment]
For e.g. the wording "Leading" is used 6 times on the web page but appear only twice in the Source file.

**Comment by horiguti** [comment]
Sorry for the laziness.  Now github is the main repository of this project and it won't get behind again, maybe.
