### ISSUE TITLE
Memory not freed in time when debug_print is set to verbose

### ISSUE THREAD

**Issue by sherlockcpp** [ossc-db/pg_hint_plan#50]
Hi
I  found some Memory not freed in time when debug_print is set to verbose
in function ``` restrict_indexes() ```

when debug_level > 0 , buf malloc 1024 bytes
```cpp
	if (debug_level > 0)
		initStringInfo(&buf);
```
at the end of ``` restrict_indexes() ``` , buf.data is freed only if debug_level = 1. 
I think buf.data is not freed in time when debug_level is 2 or 3.
        [ps. After my check, is does not cause memleak]
```cpp
	if (debug_level == 1)
	{
		initStringInfo(&rel_buf);
                ...
		pfree(buf.data);
		pfree(rel_buf.data);
	}
```
I think  a new if branch can be create to free buf.data, like the following;
```cpp
	if (debug_level == 1)
	{
		initStringInfo(&rel_buf);
                ...
		pfree(rel_buf.data);
	}

	if (debug_level > 0)
		pfree(buf.data);
```

**Comment by horiguti** [comment]
It is already fixed at master.  but don't be so nervous about that:p  The memory will be freed up at the end of query.  In some sense the pfree is not required at all.
That being said it is not neat that the code behaves differently for subtle conditions.
I committed that change in the PG13 branch in the repo.
