### ISSUE TITLE
where to place hint in procedure 

### ISSUE THREAD

**Issue by SeanKimMel** [ossc-db/pg_hint_plan#55]
hi there, I'd like to report interesting find during my work.

I have tested pg_hint_plan 1.3.5 version on PG 11.7

the part that I have tested is using hint inside of the procedure.

few times I have tried and noticed that hint is not working on insert statement unless

I place the hint after "INSERT INTO "

select statements seems working fine if hint is placed before "SELECT"

I'll update this post when I have time to test more later.

**Comment by kasaharatt** [comment]
Could you share your procedure code and actual plan information which the HINT clause works and not works.
If specifying a HINT clause after INSERT works, then specifying it before INSERT also works, I think.

Here are some simple test results.


Make the following parameter changes to postgresql.conf and restrt PostgreSQL.
=======================================================
shared_preload_libraries = 'pg_hint_plan, auto_explain'
auto_explain.log_min_duration = 0
auto_explain.log_analyze = on
auto_explain.log_nested_statements = on
=======================================================

Create tables, insert records, and make a funtion.
==========================================================
CREATE TABLE src (c1 int PRIMARY KEY);
CREATE TABLE dst (c1 int);
INSERT INTO src SELECT generate_series(1,10000);
VACUUM ANALYZE src;


CREATE OR REPLACE FUNCTION test_f(int) RETURNS void AS
$$
DECLARE
  num int := $1;
BEGIN
  EXECUTE 'INSERT INTO dst SELECT c1 from src WHERE c1 < $1' USING num;
  EXECUTE 'INSERT INTO dst /*+ SeqScan (src) */  SELECT c1 from src WHERE c1 < $1' USING num;
  EXECUTE '/*+ SeqScan (src) */  INSERT INTO dst SELECT c1 from src WHERE c1 < $1' USING num;
END;
$$
language plpgsql;
==========================================================

After executing the function, the following output is given to the log.

==========================================================
2020-07-02 12:26:44.047 JST [21140] LOG:  duration: 0.025 ms  plan:
        Query Text: INSERT INTO dst SELECT c1 from src WHERE c1 < $1
        Insert on dst  (cost=0.29..4.44 rows=9 width=4) (actual time=0.024..0.024 rows=0 loops=1)
          ->  Index Only Scan using src_pkey on src  (cost=0.29..4.44 rows=9 width=4) (actual time=0.005..0.007 rows=9 loops=1)
                Index Cond: (c1 < 10)
                Heap Fetches: 0
2020-07-02 12:26:44.047 JST [21140] CONTEXT:  SQL statement "INSERT INTO dst SELECT c1 from src WHERE c1 < $1"
        PL/pgSQL function test_f(integer) line 5 at EXECUTE


2020-07-02 12:26:44.048 JST [21140] LOG:  duration: 0.517 ms  plan:
        Query Text: INSERT INTO dst /*+ SeqScan (src) */  SELECT c1 from src WHERE c1 < $1
        Insert on dst  (cost=0.00..170.00 rows=9 width=4) (actual time=0.516..0.516 rows=0 loops=1)
          ->  Seq Scan on src  (cost=0.00..170.00 rows=9 width=4) (actual time=0.008..0.508 rows=9 loops=1)
                Filter: (c1 < 10)
                Rows Removed by Filter: 9991
2020-07-02 12:26:44.048 JST [21140] CONTEXT:  SQL statement "INSERT INTO dst /*+ SeqScan (src) */  SELECT c1 from src WHERE c1 < $1"
        PL/pgSQL function test_f(integer) line 6 at EXECUTE


2020-07-02 12:26:44.048 JST [21140] LOG:  duration: 0.513 ms  plan:
        Query Text: /*+ SeqScan (src) */  INSERT INTO dst SELECT c1 from src WHERE c1 < $1
        Insert on dst  (cost=0.00..170.00 rows=9 width=4) (actual time=0.513..0.513 rows=0 loops=1)
          ->  Seq Scan on src  (cost=0.00..170.00 rows=9 width=4) (actual time=0.005..0.505 rows=9 loops=1)
                Filter: (c1 < 10)
                Rows Removed by Filter: 9991
2020-07-02 12:26:44.048 JST [21140] CONTEXT:  SQL statement "/*+ SeqScan (src) */  INSERT INTO dst SELECT c1 from src WHERE c1 < $1"
==========================================================

As above, the HINT clause works (force Seq Scan) whether it is before or after INSERT.

**Comment by SeanKimMel** [comment]
thanks a lot!!
