### ISSUE TITLE
Installation of pg_hint_plan failed

### ISSUE THREAD

**Issue by chinagui** [ossc-db/pg_hint_plan#57]
#### Environment
- [x] Operating System: CentOS 7.5
- [x] PostgreSQL version：PostgreSQL 11.x
- [x] pg_hint_plan version: REL11_1_3_6 

When I execute the make command in the pg_hint_plan-REL11_1_3_6 directory, the following error appears:

gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o pg_hint_plan.o pg_hint_plan.c
pg_hint_plan.c:34:37: fatal error: partitioning/partbounds.h: No such file or directory
 #include "partitioning/partbounds.h"
                                     ^
compilation terminated.
make: *** [pg_hint_plan.o] Error 1
[root@r1-coremap-kftest-vm-3 pg_hint_plan-REL11_1_3_5]# pwd
/usr/local/pg-hint-plan/pg_hint_plan-REL11_1_3_5

**Comment by kasaharatt** [comment]
Hi.

Which PostgreSQL  version did you install ?  PostgreSQL 11.x ?
It seems to me that you installed Inappropriate PostgreSQL version for pg_hint_plan-REL11.
Or if you installed PostgreSQL 11.x, please check your (root's) $PATH environment variable correctly sets to PostgreSQL 11.x bin directory.

regards,

**Comment by chinagui** [comment]
Thanks for the reply.
Yes，the postgresql version I use is 11. I have added PostgreSQL bin directory to $PATH Before installing pg_hint_plan.

**Comment by kasaharatt** [comment]
Hi,
Do you have any other PostgreSQL version in the environment ?
Which PATH did you install PostgreSQL 11.x ? 

Or if you used RPM packages, you need a postgresql11-devel. Did you install this devel package? 

regards,

**Comment by chinagui** [comment]
Yes ! Postgresq-devel package is not installed on my machine.  Pg_hint_plan is now successfully installed. Thank you for your help !
