### ISSUE TITLE
unable to update extension

### ISSUE THREAD

**Issue by 20hyun** [ossc-db/pg_hint_plan#60]
Hi, 
In a797bcf944d7f5c17d6d26cdaa2c57ef50b73a81 , It seems line break leads to syntax error when updating extension.
```
/* pg_hint_plan/pg_hint_plan--1.3.6--1.3.7.sql */

-- complain if script is sourced in psql, rather than via CREATE EXTENSION
\echo Use "ALTER EXTENSION pg_dbms_stats UPDATE TO '1.3.7'" to load this file.
\quit
```

```
postgres=# CREATE EXTENSION pg_hint_plan VERSION "1.3.6";
CREATE EXTENSION
postgres=# ALTER EXTENSION pg_hint_plan UPDATE TO "1.3.7";
ERROR:  syntax error at or near "\"
postgres=# \dx pg_hint_plan 
           List of installed extensions
     Name     | Version |  Schema   | Description 
--------------+---------+-----------+-------------
 pg_hint_plan | 1.3.6   | hint_plan | 
(1 row)
```

By editing complain back to one line made work as normal
```
/* pg_hint_plan/pg_hint_plan--1.3.6--1.3.7.sql */

-- complain if script is sourced in psql, rather than via CREATE EXTENSION
\echo Use "ALTER EXTENSION pg_dbms_stats UPDATE TO '1.3.7'" to load this file. \quit
```

```
postgres=# ALTER EXTENSION pg_hint_plan UPDATE TO "1.3.7";
ALTER EXTENSION
postgres=# \dx pg_hint_plan 
           List of installed extensions
     Name     | Version |  Schema   | Description 
--------------+---------+-----------+-------------
 pg_hint_plan | 1.3.7   | hint_plan | 
(1 row)
```

**Comment by rjuju** [comment]
It's worth noting that the new approach taken upstream is only valid for pg10+.  Since we don't support EOL major versions I agree that we should use the same approach and keep the initial full SQL file and only provide upgrade scripts from there, and keep doing that for newer versions.

**Comment by michaelpq** [comment]
> It's worth noting that the new approach taken upstream is only valid for pg10+. Since we don't support EOL major versions I agree that we should use the same approach and keep the initial full SQL file and only provide upgrade scripts from there, and keep doing that for newer versions.

What should we do for versions between each branch? PG14/master are on 1.4 for example. Do you think that we should also have upgrade paths from 1.3.X to 1.4 or even future versions? I am not sure what this implies in terms of complexity and binary compatibility, TBH (for example of function arguments have changed, we need to keep track of the function at run-time like pg_stat_statements, or if results are changed we can adapt the returned tuple dynamically).

**Comment by michaelpq** [comment]
Proposal of patch sent here: https://github.com/ossc-db/pg_hint_plan/pull/111
