### ISSUE TITLE
The default value of pg_hint_plan.message_level is not same with document

### ISSUE THREAD

**Issue by ChenJiaoqian** [ossc-db/pg_hint_plan#62]
Hello, when I print the default value of pg_hint_plan.message_level, I found it is not same with the value on document.
The value on document is "INFO", but it prints "LOG".

The information on document:
Parameter name: pg_hint_plan.message_level
discription: Specifies message level of debug print. Valid values are error, warning, notice, info, log, debug.
Default: INFO

Execute log:
```
postgres=# load 'pg_hint_plan';
LOAD
postgres=# create extension pg_hint_plan;
CREATE EXTENSION
postgres=# select name, setting from pg_settings where name = 'pg_hint_plan.message_level';
            name            | setting
----------------------------+---------
 pg_hint_plan.message_level | log
(1 row)

postgres=#
```

**Comment by michaelpq** [comment]
This has been applied only on PG14~, and PG10~13 have missed the update. Done now.
