### ISSUE TITLE
The test set of PG96 needs to be updated.

### ISSUE THREAD

**Issue by qianglingjie** [ossc-db/pg_hint_plan#75]
Same as https://github.com/ossc-db/pg_hint_plan/commit/8286b67632d538219d9f0c0a7fef0b404f307792 commit https://github.com/postgres/postgres/commit/37681d7e942e31256efdd9b562a750f1742ac111 has also changed the core's behavior of naming indexes in PG96. However, branch PG96 have not follow the mentioned behavioral change above yet,  so I think it is necessary to update branch PG96's master log  like other branches.

**Comment by horiguti** [comment]
There can be a case where the PostgreSQL side change cusae the regression tests fail. But I don't want to maintain followng every PostgreSQL behavioral change.  Addition to that, PG96 is log ago EOLed.  Sorry but I won't do that except when some serious bug is fixed.
