### ISSUE TITLE
Official support for PostgreSQL 14?

### ISSUE THREAD

**Issue by robert-pang** [ossc-db/pg_hint_plan#79]
The current release of pg_hint_plan is 1.3.7 that supports up to PostgreSQL 13. I see a couple of new commits 2 weeks ago that update the version to 1.4 with the support for PostgreSQL 14.

May I ask if there is a target date when version 1.4 will be released officially?

Thank you.

**Comment by horiguti** [comment]
Sorry for being late.  It'll be soon released.

**Comment by michaelpq** [comment]
We are working on it.
