### ISSUE TITLE
[BUG]Duplicate Memoize cannot be checked

### ISSUE THREAD

**Issue by ShangBenX** [ossc-db/pg_hint_plan#83]
* Problem description

  In an SQL query, a bug occurs when repeated Memoize/NoMemoize is used.

* Bug reproduce

  Environment：

  OSS:14.1

  pg_hint_plan:master(commit#cde640fdefad9b0d6cc50985fdf93eb50bf01903)

  ```sql
  postgres=# load 'pg_hint_plan';
  LOAD
  postgres=# create table test_hint_table(id int, val text);
  CREATE TABLE
  postgres=# /*+ Memoize(t1 t2) Memoize(t1 t2) */ explain  select * from test_hint_table t1, test_hint_table t2 where t1.id=t2.id;
  server closed the connection unexpectedly
  	This probably means the server terminated abnormally
  	before or while processing the request.
  The connection to the server was lost. Attempting reset: Failed.
  !?> 
  ```

* Bug analysis

  The enumeration HintType and array HintTypeName elements do not match.

  * HintType

    ```c
    /* hint types */
    typedef enum HintType
    {
  	  HINT_TYPE_SCAN_METHOD,
  	  HINT_TYPE_JOIN_METHOD,
  	  HINT_TYPE_LEADING,
  	  HINT_TYPE_SET,
  	  HINT_TYPE_ROWS,
  	  HINT_TYPE_PARALLEL,
  	  HINT_TYPE_MEMOIZE,
    
  	  NUM_HINT_TYPE
    } HintType;
    ```

  * HintTypeName

    ```c
    static const char *HintTypeName[] = {
    	"scan method",
    	"join method",
    	"leading",
    	"set",
    	"rows",
    	"parallel"
    };
    ```

    The "memoize" element is missing from array HintTypeName.

  * The Bug is resolved when the element "memoize" is added to the array HintTypeName.

**Comment by horiguti** [comment]
Thanks for the analysis!

I saw "DETAIL:  Conflict (null) hint." for the trouble but that could be SEGV on other platforms.
I added the missing item and added statis assertion.
