### ISSUE TITLE
Ignore hints in prepared statements with array arguments

### ISSUE THREAD

**Issue by WinterUnicorn** [ossc-db/pg_hint_plan#94]
Case to reproduce:
We have an issues with prepared statements that use arrays in arguments.
In this case pg_hint_plan don't pass preceding sql check.
Is it possible to adds '[', ']' symbols into the white list?

```
prepare test_query(numeric[]) as /*+ MergeJoin(t1 t2) */ with test as (select 1 as x) select t1.* from test t1, test t2 where t1.x=any($1) and t1.x = t2.x;
explain execute test_query(array[1,2,3]); 
-- MergeJoin hint will be ignore because of numeric[]
deallocate test_query;
```

**Comment by WinterUnicorn** [comment]
Dear @horiguti 
can you review the issue please
Questions are welcome

**Comment by WinterUnicorn** [comment]
@Anisimov-ds  @rattrayalex I see that you have committed in this repository. Do you know what contributor can I contact for a discussion or review?

**Comment by WinterUnicorn** [comment]
Related pull request:  https://github.com/ossc-db/pg_hint_plan/pull/98

**Comment by michaelpq** [comment]
Sorry for the time it took to reply back. I am going to review what you have here. It does not look like a bad idea in itself, still I am wondering about one thing. Shouldn't we treat this as a new feature? From what I can see, this may imply a behavior change for existing users, which may not be wise to backpatch into existing releases.

@rjuju, @MasahikoSawada, @horiguti, please feel free to share your thoughts or just contradict me.
